Update pre-commit script.
And then switch to not using it.

diff --git a/TEMPLATE/pre-commit b/TEMPLATE/pre-commit
--- a/TEMPLATE/pre-commit
+++ b/TEMPLATE/pre-commit
@@ -1,60 +1,115 @@
 #!/bin/bash
+# https://raw.github.com/gini/puppet-git-hooks/master/hooks/pre-commit
+
+# External requirements:
 #
-# https://raw.github.com/drwahl/puppet-git-hooks/master/pre-commit
+#    * Git
+#    * sed
+#    * Ruby with ERB and YAML support
+#    * Puppet >= 2.7
+#    * puppet-lint
+#
+#    Adjust LINTFLAGS as appropriate
 
-git_root=`git rev-parse --show-toplevel`
+# Redirect output to stderr.
+exec 1>&2
 
-syntax_errors=0
-error_msg=$(mktemp /tmp/error_msg.XXXXXX)
+PUPPETLINT_FLAGS=${PUPPETLINT_FLAGS:-'--no-autoloader_layout-check --no-80chars-check'}
+TMPDIR=${TMPDIR:-'/tmp'}
+TMPFILE=$(mktemp "${TMPDIR}"/tmp.XXXXXXXXXX)
+STATUS=0
 
+# Register exit trap for removing temporary files
+trap 'rm -rf $TMPFILE' EXIT INT HUP
+
+# Check for ruby binary
+which ruby >/dev/null 2>&1 || exit 1
+
+# Check for Puppet binary
+which puppet >/dev/null 2>&1 || exit 1
+
+# Check for puppet-lint
+which puppet-lint >/dev/null 2>&1 || exit 1
+
+# Check for erb
+which erb >/dev/null 2>&1 || exit 1
+
+# Get correct git revision
 if git rev-parse --quiet --verify HEAD > /dev/null
 then
-    against=HEAD
+    revision=HEAD
 else
     # Initial commit: diff against an empty tree object
-    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
+    revision=4b825dc642cb6eb9a060e54bf8d69288fbee4904
 fi
 
-# Get list of new/modified manifest and template files to check (in git index)
-for puppetmodule in `git diff --cached --name-only --diff-filter=ACM | grep '\.*.pp$\|\.*.erb$'`
+IFS="
+ "
+
+# Get a list of files changed in this transaction
+declare -a FILES
+FILES=$(git diff --cached --name-only --diff-filter=ACM "${revision}")
+
+for file in ${FILES[@]}
 do
     # Don't check empty files
-    case $puppetmodule in
-        *.pp )
-            # Check puppet manifest syntax
-            echo -e "Validate Puppet module: \033[0;32m$puppetmodule\033[0m"
-            puppet parser validate --color=true "$git_root/$puppetmodule" > $error_msg ;;
-        *.erb )
-            # Check ERB template syntax
-            echo -e "Validate Puppet template: \033[0;32m$puppetmodule\033[0m"
-            erb -P -x -T '-' "$git_root/$puppetmodule" | ruby -c 2> $error_msg > /dev/null ;;
-    esac
-    if [ $? -ne 0 ]
-    then
-        echo -n "$indexfile: "
-        cat $error_msg
-        syntax_errors=`expr $syntax_errors + 1`
+    if [[ $(git cat-file -s ":0:${file}") -eq 0 ]]; then
+        continue
+    fi
+
+    extension="${file##*.}"
+    git cat-file blob ":0:${file}" > $TMPFILE
+
+    if [[ $? -ne 0 ]]; then
+        echo "Unable to checkout ${file}"
+        STATUS=2
+    else
+        case $extension in
+            pp)
+                # Remove import lines while parsing
+                # http://projects.puppetlabs.com/issues/9670#note-14
+                sed -i -e '/^import / d' $TMPFILE >/dev/null 2>&1
+                # Puppet syntax check
+                puppet parser validate $TMPFILE >/dev/null 2>&1
+                if [[ $? -ne 0 ]]; then
+                    echo "Puppet syntax error in ${file}. Run 'puppet parser validate ${file}'" >&2
+                    STATUS=2
+                fi
+
+                # puppet-lint check
+                puppet-lint $PUPPETLINT_FLAGS --log-format "${file}:%{linenumber} %{KIND} - %{message}" $TMPFILE 2> /dev/null
+                if [[ $? -ne 0 ]] ; then
+                    STATUS=2
+                fi
+            ;;
+    
+            erb)
+                # syntax check templates - this doesn't catch a lot of mistakes,
+                # but it should catch gross mistakes
+                erb -x -T - "${TMPFILE}" | ruby -c >/dev/null 2>&1
+                if [[ $? -ne 0 ]]; then
+                    echo "ERB syntax error in ${file}" >&2
+                    STATUS=2
+                fi
+            ;;
+            yml|yaml)
+                # syntax YAML files, https://ttboj.wordpress.com/2013/08/25/finding-yaml-errors-in-puppet/
+                ruby -ryaml -e "YAML.parse(File.open('${TMPFILE}'))" >/dev/null 2>&1
+                if [[ $? -ne 0 ]]; then
+                    echo "YAML syntax error in ${file}" >&2
+                    STATUS=2
+                fi
+            ;;
+            json)
+                # syntax YAML files, https://ttboj.wordpress.com/2013/08/25/finding-yaml-errors-in-puppet/
+                ruby -rjson -e "JSON.parse(File.open('${TMPFILE}').read)" >/dev/null 2>&1
+                if [[ $? -ne 0 ]]; then
+                    echo "JSON syntax error in ${file}" >&2
+                    STATUS=2
+                fi
+            ;;
+        esac
     fi
 done
 
-rm -f $error_msg
-
-if [ "$syntax_errors" -ne 0 ]
-then
-    echo -e "\033[0;31mError: $syntax_errors syntax errors found, aborting commit.\033[0m"
-    exit 1
-fi
-
-# De-lint puppet manifests
-if [ `which puppet-lint` ]; then
-    for puppetmodule in `git diff --cached --name-only --diff-filter=ACM | grep \.*.pp$`; do
-        echo -e "Style check for Puppet module: \033[0;32m$puppetmodule\033[0m"
-        puppet-lint --fail-on-warnings --with-filename --no-80chars-check --no-double_quoted_strings-check "$git_root/$puppetmodule"
-        RC=$?
-        if [ $RC -ne 0 ]; then
-            exit $RC
-        fi
-    done
-fi
-
-exit 0
+exit $STATUS
